---

- name: converge
  hosts: all
  any_errors_fatal: false
  gather_facts: true

  environment:
    NETRC: ''

  roles:
    - role: ansible-container

# ----------------------------------------------------------------------------------

- name: update
  hosts: all
  any_errors_fatal: false
  gather_facts: true

  environment:
    NETRC: ''

  vars:
    container:
      - name: busybox
        hostname: busybox
        image: busybox:latest

  roles:
    - role: ansible-container

...
