---

- name: execute pre tasks
  command: |
    {{ item }}
  args:
    warn: false
  changed_when: false
  register: _pre_task_output
  loop: "{{ container_pre_tasks }}"

- name: result
  debug:
    msg:
      - "{{ item.stdout }}"
  loop: "{{ _pre_task_output.results }}"
  loop_control:
    label: "{{ item.item }}"

...
