---

- name: create docker network
  docker_network:
    name: "{{ item.name }}"
    enable_ipv6: false
    ipam_config:
      - subnet: "{{ item.subnet }}"
        gateway: "{{ item.gateway }}"
        iprange: "{{ item.iprange }}"
  loop: "{{ container_network }}"
  loop_control:
    label: "{{ item.name.ljust(12) }}: {{ item.iprange }}"
  when: container_use_network

...
