---

- name: ensure tasks are available
  stat:
    path: "{{ item }}"
    get_checksum: false
    get_md5: false
    get_mime: false
    get_attributes: false
    register: _post_task_available

- name: debuf
  debug:
    msg: "{{ _post_task_available }}"

...
