---

container:
  - name: hello-world
    hostname: hello-world
    image: hello-world:latest
    properties:
      #
      publisher.maxRecursionDepth: 200
      # user and password for login to the staging serve
      replicator.user: 'replicator'
      replicator.password: 'replicator'
      # replicator.domain: ''
      replicator.tmp_dir: 'var/tmp'

container_post_tasks:
  - /usr/local/bin/list_all_images.sh
  - /usr/local/bin/remove_untagged_images.sh

...
