---

container_network:
  - name: test
    subnet: 172.3.27.0/24
    gateway: 172.3.27.2
    iprange: 172.3.27.0/26

  - name: monitoring
    enable_ipv6: false
    subnet: 172.9.27.0/24
    gateway: 172.9.27.2
    iprange: 172.9.27.0/26

container:
  - name: nginx-proxy
    hostname: nginx-prox
    image: jwilder/nginx-proxy
    published_ports:
      - 80:80
    volumes:
      - /run/docker.sock:/run/docker.sock:ro
      - /tmp/nginx:/tmp/nginx:ro
      - /dev/foo:/dev/foo:ro
      - testing1:/var/tmp/testing1|{owner="1000",group="1000",mode="0755"}
      - testing2:/var/tmp/testing2|{owner="800",group="999",mode="0700"}
      - testing3:/var/tmp/testing3:rw|{owner="999",group="1000"}
      - testing4:/var/tmp/testing4|{owner="1001",mode="0700"}

  - name: whoami
    state: absent
    image: jwilder/whoami
    environments:
      VIRTUAL_HOST: whoami.local

...
