---

container_network:
  - name: test
    subnet: 172.3.27.0/24
    gateway: 172.3.27.2
    iprange: 172.3.27.0/26

  - name: monitoring
    enable_ipv6: false
    subnet: 172.9.27.0/24
    gateway: 172.9.27.2
    iprange: 172.9.27.0/26

container:
  - name: nginx-proxy
    hostname: nginx-prox
    image: jwilder/nginx-proxy
    published_ports:
      - 80:80
    volumes:
      - /run/docker.sock:/run/docker.sock:ro
      - /tmp/nginx:/tmp/nginx:ro
      - /dev/foo:/dev/foo:ro

  - name: whoami
    state: absent
    image: jwilder/whoami
    environments:
      VIRTUAL_HOST: whoami.local

...
